apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-job
spec:
  schedule: {{ .Values.cronjob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}-job
            image: {{ .Values.cronjob.image }}:{{ .Values.cronjob.tag }}
            command:
            {{- range .Values.cronjob.command }}
              - {{ quote . }}
            {{- end }}
            args:
            {{- range .Values.cronjob.args }}
              - {{ quote . }}
            {{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}