apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: api
      role: web
  template:
    metadata:
      labels:
        app: api
        role: web
    spec:
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      containers:
        - name: {{ .Release.Name }}-web
          image: {{ .Values.web.repository }}:{{ .Values.web.tag }}
          ports:
            - name: gunicorn
              containerPort: 5000
          # readinessProbe:
          #   initialDelaySeconds: 10
          #   httpGet:
          #     port: gunicorn
          #     path: /
          # livenessProbe:
          #   initialDelaySeconds: 10
          #   exec:
          #     command:
          #       - /bin/sh
          #       - -c 
          #       - "pidof -x gunicorn"

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: api
    role: web
  ports:
    - name: http
      port: 80
      targetPort: gunicorn